version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - app-data:/app/data
    environment:
      - CGO_ENABLED=1

volumes:
  app-data:
